#!/bin/bash
x=`find "$1" -maxdepth 1 -type f | wc -l` ##number of files in the directory
(( y=$x-$3 )) #the last file to keep
(( z=$2+1 ))  #the first file to keep
echo `find "$1" -maxdepth 1 -type f | sort | sed -n "$z","$y"p` | tr " " "\n"

#to check this option: echo find "$1" -maxdepth 1 -type f | sort | sed -n "$z","$y"p
